In [1]:
import json
import pandas as pd

In [8]:
records = []
with open("../data/raw_metadata.jsonl", encoding="utf-8") as f:
    for line in f:
        records.append(json.loads(line))

In [11]:
df = pd.DataFrame(records)

In [36]:
df[df['id'].str.contains('2606.20220')]

,id,title,abstract,categories,primary_category,published,updated,authors
69067,2606.20220v3,Higher-loop wormhole length in sine-dilaton gr...,The quantum wormhole length in sine-dilaton gr...,[hep-th],hep-th,2026-06-18T13:35:38Z,2026-06-29T07:29:04Z,"[Eleonora Alfinito, Matteo Beccaria]"

In [35]:
df[df['id'].str.contains('v3')].tail(5)

,id,title,abstract,categories,primary_category,published,updated,authors
68986,2606.18639v3,A Note on Corrections to Entanglement Wedge Re...,"If entanglement wedge reconstruction is exact,...",[hep-th],hep-th,2026-06-17T03:22:29Z,2026-07-10T14:35:32Z,[Edward Witten]
69067,2606.20220v3,Higher-loop wormhole length in sine-dilaton gr...,The quantum wormhole length in sine-dilaton gr...,[hep-th],hep-th,2026-06-18T13:35:38Z,2026-06-29T07:29:04Z,"[Eleonora Alfinito, Matteo Beccaria]"
69115,2606.21079v3,Linear Growth of Holographic Time-like Entangl...,The holographic time-like entanglement entropy...,"[hep-th, gr-qc]",hep-th,2026-06-19T03:59:53Z,2026-07-13T05:58:14Z,"[Zi-Hao Li, Run-Qiu Yang]"
69175,2606.22531v3,Steering a warp drive without exotic matter,"A useful warp drive must accelerate, yet every...","[gr-qc, hep-th]",gr-qc,2026-06-21T14:42:06Z,2026-07-15T01:29:18Z,[An T. Le]
69247,2606.24008v3,General Lagrangian formulations for mixed-anti...,Lagrangian formulations for (ir)reducible inte...,"[hep-th, math-ph, math.DS, math.RT]",hep-th,2026-06-22T23:28:53Z,2026-07-04T01:15:39Z,[Alexander A. Reshetnyak]